version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_greenlight
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: greenlight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/greenlight
volumes:
  postgres_data: